---
title: "Gov 50 Final Project"
author: "Ethan Fang"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project Thoughts

I am interested in exploring data related to disability advocacy, race, and gender theory. More specifically, one idea regarding disability justice is seeing how college rates differ amongst students who classify as having a disability versus not, controlling for standardized test scores. Another idea is examining the effect of redlining practices. Lastly, I could do a project about climate change.  

## One Paragraph Proposal

Are the social and economic ramifications of redlining still prevalent today? In this study, I plan to examine the extent to which regions in Cambridge display the longer-term effects of redlining practices. As part of the Harvard Public Opinion Project (HPOP), I helped advance an investigation on affordable housing and poverty infrastructure in Cambridge and the greater Boston area, and further extrapolated polling findings to the country at large. 

Through these, I hypothesize that Cambridge's minority communities are disproportionately represented in areas of higher socioeconoimc stress -- due not only to matters of personal sorting or preference, but moreso due to systemic factors propogating from decades of redlining practices riddled with historical discrimination. One of the most salient effects of redlining was the development of segregated neighborhoods. By denying loans to residents of certain neighborhoods, financial institutions created a concentration of poverty in these areas. 

My dataset for this project will be the Opportunity Atlas, which contains data on adult incomes, racial breakdown, parent incomes, and more. My sample, from the Opportunity Atlas, will contain anonymous data following 20 million Americans from childhood to their mid-30s (collected from de-identified data from the 2000 and 2010 decennial Censuses). My unit of analysis is a specific ZIP code representing a small region, or in other words, my individual datapoints each represent one ZIP code. The primary explanatory variable is the racial composition of different areas, measured by the proportion of white and black residents. This data can be obtained from census records, which provide detailed, comprehensive demographic data broken down by racial and ethnic groups at various geographical levels, ensuring variation in the racial composition across different areas. I will be analyzing the outcome variable of absolute mobility at the 25th percentile, and to do so, I will use the predicted rank of a child for a given parent's income rank, labeled as kfr_pooled_pooled_p25, for which units are measured as the mean percentile rank according to the 2010 decennial Census. For this metric, higher values will correspond with higher upward mobility.

If the trend saw that ZIP codes with higher proportions of white people had higher average mobility than ZIP codes with high proportions of minorities, then this data would support my hypothesis. If the trend saw that ZIP codes with higher proportions of white people had similar or smaller average mobility than ZIP codes with high proportions of minorities, then this observed data pattern would disprove my hypothesis. When I run a regression for correlation between proportion of white people and average mobility, a positive, significant coefficient would indicate support for my hypothesis.

## Visualization Showing Link
```{r, echo=FALSE}
library(haven)
library(tidyverse)
library(ggplot2)
library(tidyverse) #data science tools
library(haven) # enables transfer between stata, R, etc
library(ggplot2) # graphing tools
library(statar) # stata commands in R
library(scales) # add commas 
#library(dplyr) = data manipulation tools 
library(sandwich)
library(lmtest)

```

Below, I demonstrate a visualization of a histogram showing the distribution of kfr_pooled_pooled_p25 (average mobility at the 25th percentile).

```{R}
atlas <- read_dta("/Users/ethan/Desktop/datlas.dta")

ggplot(atlas) + geom_histogram(aes(x=kfr_pooled_pooled_p25, y=..density..))

```

```{R}
#Creating Dataframe
#filter out NA's
data_filtered <- atlas[!is.na(atlas$kfr_pooled_pooled_p25), ]
```

Here is a visualization demonstrating the correlation between poor_share1990 and absolute mobility at the 25th percentile. Higher levels of poverty were negatively correlated with absolute mobility at the 25th percentile. 

```{R}
#create dataframe for cambridge
cambridge_df <- data_filtered[data_filtered$cz == 20500, ]

#Demonstrate Correlation between poor_share1990 and abs mobility at 25th per
  ggplot(cambridge_df, aes(x=poor_share1990, y=kfr_pooled_pooled_p25)) +
    stat_smooth(method=lm, se=FALSE) + 
    stat_binmean(n = 20, geom = "point")
  


```
